### ISSUE TITLE
Gitlab-ci test bug

### ISSUE THREAD

**Issue by elcomtik** [mrlesmithjr/cookiecutter-ansible-role#4]
I started developing a role base on this cookiecutter template and encountered an issue with gitlab-ci config. I wasn't sure if it was caused by misunderstanding. 

I tried to build your project https://github.com/mrlesmithjr/ansible-frr, which I recently developed. As you can see travis-ci https://travis-ci.org/github/mrlesmithjr/ansible-frr/builds/729608405 and also test on github https://github.com/mrlesmithjr/ansible-frr/runs/1154947400 did passed. When I tired to build on my giltab account it didn't succeded https://gitlab.com/elcomtik/ansible-frr/-/pipelines/193622331/builds. 

The ERROR can be seen on job log https://gitlab.com/elcomtik/ansible-frr/-/jobs/753720420#L293 
`ERROR: Cannot uninstall 'pep517'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

I think it's caused by apk installed python packages which conflicts with requirements, which we want to install by pip. I tested some ideas wich didn't lead to working solution. 

Do you have some project with actively used gitlab-ci tests?

Do we need to install all of these python packages? https://github.com/mrlesmithjr/ansible-frr/blob/master/.gitlab-ci.yml#L11-L14.

**Comment by mrlesmithjr** [comment]
Thanks for catching this. I'll be merging the fix for this. Basically the following works:
```yaml
before_script:
  - apk update && apk add --no-cache docker
    python3-dev py3-pip docker gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh
  - docker info
  - python3 --version
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install --upgrade pip pip-tools
  - pip-sync requirements.txt requirements-dev.txt
  - ansible --version
  - molecule --version
```

**Comment by elcomtik** [comment]
Thanks for fix
