### ISSUE TITLE
How to update existing project by cookiecutter?

### ISSUE THREAD

**Issue by elcomtik** [mrlesmithjr/cookiecutter-ansible-role#8]
Would you mind adding information about updating the existing project? I couldn't find any how-to for this.

**Comment by mrlesmithjr** [comment]
@elcomtik Can you provide me some more info on this?

**Comment by elcomtik** [comment]
I'm just curious about updating my existing roles to a most recent cookie-cutter template, is it somehow possible?

**Comment by mrlesmithjr** [comment]
Yep it is totally doable. I do it all the time as a matter of fact. I will write a how-to soon. Thanks for the reminder!

**Comment by mrlesmithjr** [comment]
Here is a quick example of how I do this. Let's use an example role named `ansible-example` for this:

First clone existing role to a temporary directory so we can bring back files needed
```bash
git clone https://github.com/mrlesmithjr/ansible-example ansible-example.orig
```

Create new role structure using Cookiecutter template (follow the flow and name the role exactly as the original role)
```bash
cookiecutter https://github.com/mrlesmithjr/cookiecutter-ansible-role
```

Once the new structure has been completed we will now delete the new `.git` directory in preparation of restoring the original files that we would like to keep or discard.
```bash
cd ansible-example
rm -rf .git
```

Next we will restore the original `.git` directory to our new project that we have used Cookiecutter for.
```bash
cp -Rv ../ansible-example.orig/.git .
```

You should now have all of the original history back into your new role structure. You can now pick and choose what to keep or discard. At the very least I will generally do the following:
```bash
git restore defaults/ handlers/ tasks/ templates/
```

Hope this helps a bit @elcomtik

**Comment by elcomtik** [comment]
Thanks, this is awesome.

**Comment by mrlesmithjr** [comment]
I just realized that I also had written up a blog post around this topic and completely forgot about it. Just wanted to add that link here for anyone else that may have similar questions.

https://everythingshouldbevirtual.com/Updating-Git-Project-Structure/
